default_config:

logger:
  default: warn
  logs:
    custom_components.nyc311: debug
    nyc311calendar: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
